package my.neomer.sixtyseconds.transport;

import my.neomer.sixtyseconds.model.Answer;
import my.neomer.sixtyseconds.model.Question;

public class FakeQuestionProvider implements IQuestionProvider {

    public FakeQuestionProvider() {
    }

    @Override
    public void setConfiguration(TransportConfiguration config) {

    }

    @Override
    public void getNextQuestion(Question.Difficulty difficulty, Callback<Question> callback) {
        Question question = new Question();
        question.setId(0);
        question.setVote(0);
        question.setDifficulty(difficulty);
        question.setText("Sample question text generated by FakeQuestionProvider");

        callback.onReady(question);
    }

    @Override
    public void getAnswer(Question question, String guess, Callback<Answer> callback) {
        Answer answer = new Answer();
        answer.setAnswer("Sample answer on the question generated by FakeQuestionProvider");
        answer.setCorrect(true);
        answer.setComment("Simple comment");

        callback.onReady(answer);
    }

    @Override
    public void like(Question question) {

    }

    @Override
    public void dislike(Question question) {

    }

}
